const express = require('express');
const router = express.Router();
const privacyPolicyController = require('../controllers/privacyPolicyController');
const termsConditionsController = require('../controllers/termsConditionsController');
const aboutUsController = require('../controllers/aboutUsController');
const faqController = require('../controllers/faqController');
const contactFormController = require('../controllers/contactFormController');
const { protect, admin } = require('../middleware/authMiddleware');
router.get('/privacy-policy', privacyPolicyController.getPrivacyPolicy);
router.get('/terms-conditions', termsConditionsController.getTermsConditions);
router.get('/about-us', aboutUsController.getAboutUs);
router.get('/faq', faqController.getAllFAQs);
router.get('/faq/:id', faqController.getFAQById);
router.patch('/faq/:id/helpful', faqController.markHelpful);
router.post('/contact', contactFormController.submitContact);
router.get('/admin/privacy-policy', protect, admin, privacyPolicyController.getPrivacyPolicyAdmin);
router.post('/admin/privacy-policy', protect, admin, privacyPolicyController.updatePrivacyPolicy);
router.put('/admin/privacy-policy', protect, admin, privacyPolicyController.updatePrivacyPolicy);
router.get('/admin/terms-conditions', protect, admin, termsConditionsController.getTermsConditionsAdmin);
router.post('/admin/terms-conditions', protect, admin, termsConditionsController.updateTermsConditions);
router.put('/admin/terms-conditions', protect, admin, termsConditionsController.updateTermsConditions);
router.get('/admin/about-us', protect, admin, aboutUsController.getAboutUsAdmin);
router.post('/admin/about-us', protect, admin, aboutUsController.updateAboutUs);
router.put('/admin/about-us', protect, admin, aboutUsController.updateAboutUs);
router.get('/admin/faq', protect, admin, faqController.getAllFAQsAdmin);
router.post('/admin/faq', protect, admin, faqController.createFAQ);
router.put('/admin/faq/:id', protect, admin, faqController.updateFAQ);
router.delete('/admin/faq/:id', protect, admin, faqController.deleteFAQ);
router.put('/admin/faq/reorder', protect, admin, faqController.reorderFAQs);
router.get('/admin/contact', protect, admin, contactFormController.getAllContacts);
router.get('/admin/contact/stats', protect, admin, contactFormController.getContactStats);
router.get('/admin/contact/:id', protect, admin, contactFormController.getContactById);
router.put('/admin/contact/:id/reply', protect, admin, contactFormController.replyContact);
router.put('/admin/contact/:id/close', protect, admin, contactFormController.closeContact);
router.delete('/admin/contact/:id', protect, admin, contactFormController.deleteContact);
module.exports = router;
